# Generated by Django 4.1.5 on 2023-03-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="channels",
            field=models.ManyToManyField(to="app.channel"),
        ),
    ]
